# Tirando conclusões usando groupby

In [1]:
# Carregue o arquivo `winequality_edited.csv`

import pandas as pd
import numpy as np

% matplotlib inline

df = pd.read_csv('winequality_edited.csv')

,Unnamed: 0,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

### Será que o tipo de vinho está associado a uma qualidade superior?

In [6]:
# Encontre a qualidade média de cada tipo de vinho (tinto e branco) com groupby
#df.groupby(['quality','color'], as_index=False)['pH'].mean()
df.groupby(['color'], as_index=False)['quality'].mean()

   color   quality
0    red  5.636023
1  white  5.877909

### Qual o nível de acidez que recebe a maior avaliação média?

In [9]:
# Observe os seguintes valores de pH com Pandas describe: min, 25%, 50%, 75% e max
df['pH'].describe()

count    6497.000000
mean        3.218501
std         0.160787
min         2.720000
25%         3.110000
50%         3.210000
75%         3.320000
max         4.010000
Name: pH, dtype: float64

In [10]:
# Bordas dos intervalos que serão usados para dividir os dados em grupos
bin_edges = [ 2.720000,3.110000,3.210000,3.320000,4.010000] 
# Preencha esta lista com os cinco valores que você acabou de encontrar

In [34]:
# Rótulos para os quadro grupos de nível de acidez
bin_names = ['min','25%','50%','75%'] # Nomeie cada categoria de nível de acidez

In [35]:
# Cria a coluna acidity_levels
df['acidity_levels'] = pd.cut(df['pH'], bin_edges, labels=bin_names)

# Verifica se esta coluna foi criada corretamente
df.head()

,Unnamed: 0,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color,acidity_levels
0,0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,75%
1,1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red,25%
2,2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red,50%
3,3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red,25%
4,4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,75%

In [36]:
# Encontre a qualidade média de cada nível de acidez com groupby
df.groupby(['acidity_levels'], as_index=False)['pH'].mean()
#df.groupby(['acidity_levels'])['pH'].mean()

  acidity_levels        pH
0            min  3.029062
1            25%  3.164833
2            50%  3.267010
3            75%  3.433348

In [ ]:
# Salve alterações para a próxima seção
df.to_csv('winequality_edited.csv', index=False)